### ISSUE TITLE
Create API for retrieving all FocusItems for a Program

### ISSUE THREAD

**Issue by jvt** [jvt/Brainy-Kids#87]
Create an API `/api/program/:id/focusitem/` which returns all FocusItems that have that `program` key.

- Returns a 404 if the Program doesn't exist
- Returns a properly formatted JSON response with all focusitems related to that Program
- Should be protected by JWT authentication

**Comment by alkenerly** [comment]
> Create an API `/api/program/:id/focusitem/` which returns all FocusItems that have that `program` key.
> 
> * Returns a 404 if the Program doesn't exist
> * Returns a properly formatted JSON response with all focusitems related to that Program
> * Should be protected by JWT authentication

Joe, should we consider having this return an empty array if no focus items are found? That could more closely match what the other routes do.

**Comment by alkenerly** [comment]
Makes sense to me. Thats how I'll do it.
